### ISSUE TITLE
[Feature request]: Show associated chromaprint file(s) on "Manage Fingerprints" page 

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#130]
### Describe the bug

Sometimes a series or season of a show does not have intros/credits scanned for a season or episode 1 of a season etc.. It would be nice to know what the associated chromaprint files are so that I can go in and delete them/delete them from the xml file so that I can rescan them. I am not sure how trivial this would be to implement. I am assuming that this information is already being passed to the gui to access the timestamps?

### Jellyfin installation method

apt

### Operating System

Ubuntu 20.04

### Support Bundle

```shell
* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+c2727ea4e482
* Queue contents: 19349 episodes, 1243 seasons
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```
```


### Jellyfin logs

_No response_

**Comment by AbandonedCart** [comment]
The ability to delete cache for a single season is already provided in the manage window. Since fingerprints are relative to the season, deleting a single file would only recreate the same file. This should solve the root issue. As for making the files accessible, they are kept out of the UI to avoid being modified incorrectly.

**Comment by d8f6** [comment]
Okay, so does this work now? Can I close this bug?: https://github.com/jumoog/intro-skipper/issues/40

**Comment by AbandonedCart** [comment]
Well, the single episode code was abandoned in favor of fixing the manager to make sure you could always get the the delete option. It's fixed in the sense that it works as intended, but it's not necessarily what was requested.

**Comment by d8f6** [comment]
Oh, no a season at a time is optimal anyway in my opinion. I tried deleting and rescanning a season, but the credits are still not being registered. I am unsure why. I checked the logs and it says that the show was scanned so not sure what is going on. Okay, well I guess I'll close this issue and the other one if deleting the cache for a season works now/does not use the old cache timing.

**Comment by jumoog** [comment]
> Oh, no a season at a time is optimal anyway in my opinion. I tried deleting and rescanning a season, but the credits are still not being registered. I am unsure why. I checked the logs and it says that the show was scanned so not sure what is going on. Okay, well I guess I'll close this issue and the other one if deleting the cache for a season works now/does not use the old cache timing.

The results will always be the same unless you change the detection settings.

**Comment by d8f6** [comment]
I do not understand what you mean by detection settings. Is this issue not actually fixed in terms of deleting the cached data? Should I reopen?

**Comment by jumoog** [comment]
No

**Comment by d8f6** [comment]
No, it's not fixed or no, I should not reopen?????

**Comment by AbandonedCart** [comment]
It means that unless you change something, as in the amount of audio to analyze, you'll get the same results.

**Comment by d8f6** [comment]
Oh, I am looking at the wrong thread here, that's why none of this is making sense lol. The other issue is fixed though? This one: https://github.com/jumoog/intro-skipper/issues/40

**Comment by AbandonedCart** [comment]
> Well, the single episode code was abandoned in favor of fixing the manager to make sure you could always get the the delete option. It's fixed in the sense that it works as intended, but it's not necessarily what was requested.
